### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yoheitm** [yoheitm/furima-33558#10]
# URL
https://furima-33558.herokuapp.com/
# Basic認証のIDとパスワード
[id:admin][password:9617]
# 出品者用のメールアドレスとパスワード
[mail:test@com][password:abcd1234]
# 購入者用のメールアドレスとパスワード
[mail:test@test][password:1234abcd]
# 購入用カードの番号・期限・セキュリティコード
[number:4242424242424242][exp:3/22][cvc:123]

**Comment by tomoko-yokoyama** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・商品の購入ができるようにしましょう：現状、クレジットカード情報と配送先を入力しても購入ができません。
（必要項目を全て入力していますが、「Token can't be blank」という表示が出てきます）
→クレジットカード情報に誤りがある可能性もございますので、ご確認をよろしくお願いします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yoheitm** [comment]
ご確認ありがとうございます！
確認させて頂きました結果、本番環境での環境変数が未設定のままでした！
設定した後に動作を確認しましたら、問題なく購入の動作確認ができました。
すみませんが、そちらでも再度ご確認いただけますでしょうか？

**Comment by tomoko-yokoyama** [comment]
再度ご提出いただきありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by yoheitm** [comment]
ありがとうございました！
